cart/urls.py
from django.urls import path
from cart.views import add_to_cart, CartView

app_name = 'cart'

urlpatterns = [
    path("add-to-cart/<slug>", add_to_cart, name="add-to-cart"),
    path("", CartView.as_view(), name="cart"),
]

ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('home.urls', namespace='home')),
    path("cart/", include('cart.urls', namespace='cart')),
    path("accounts/", include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home.views import HomeView, CategoryItemView, ItemSearchVeiw, ItemDetailView, signup, login, logout

app_name = "home"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("category/<slug>", CategoryItemView.as_view(), name="category"),
    path("item_detail/<slug>", ItemDetailView.as_view(), name="item_detail"),
    path("search", ItemSearchVeiw.as_view(), name="search"),
    path("signup", signup, name="signup"),
    path("login", login, name="login"),
    path("logout", logout, name="logout")

]

cart/models.py
from django.db import models
from home.models import Item

# Create your models here.

class Cart(models.Model):
    username = models.CharField(max_length=100)
    items = models.ForeignKey(Item, on_delete=models.CASCADE)
    slug = models.CharField(max_length=300)
    quantity = models.IntegerField(default=1)
    checkout = models.BooleanField(default=False)
    total = models.IntegerField(default=0)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = "Cart"

home/models.py
from django.db import models
from django.urls import reverse

STATUS = (("active", "Active"), ("inactive", "Inactive"))
LABEL = (("new", "New"), ("hot", "Hot"), ("", "Default"))

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    logo = models.CharField(max_length=200)
    slug = models.CharField(max_length=100)
    status = models.CharField(choices=STATUS, max_length=100)
    
    class Meta:
        verbose_name_plural = "Category"
        
    def __str__(self):
        return self.name
    
    
class Slider(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="media")
    description = models.TextField()
    status = models.CharField(choices=STATUS, max_length=100)
    
    class Meta:
        verbose_name_plural = "Slider"

    
class Ad(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="media")
    description = models.TextField()
    rank = models.IntegerField()
    status = models.CharField(choices=STATUS, max_length=100)
    
    class Meta:
        verbose_name_plural = "Ad"
        
class Brand(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="media")
    status = models.CharField(choices=STATUS, max_length=100)
    
    class Meta:
        verbose_name_plural = "Brand"
        
    def __str__(self):
        return self.name
        
class Item(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    discounted_price = models.IntegerField(default=0)
    image = models.ImageField(upload_to="media")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    label = models.CharField(choices=LABEL, max_length=100)
    description = models.TextField(blank=True)
    specificatoin = models.TextField(blank=True)
    status = models.CharField(choices=STATUS, max_length=100)
    slug = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Item"

    def add_to_cart(self):
        return reverse('cart:add-to-cart', kwargs={'slug':self.slug})


# class Cart(models.Model):
#     username = models.CharField(max_length=100)
#     items = models.ForeignKey(Item, on_delete=models.CASCADE)
#     slug = models.CharField(max_length=300)
#     quantity = models.IntegerField(default=1)
#     checkout = models.BooleanField(default=False)
#
#     class Meta:
#         verbose_name_plural = "Cart"

cart/views.py
from django.shortcuts import render, redirect
from home.models import Item
from cart.models import Cart
from home.views import *

app_name = 'cart'

# Create your views here.

def add_to_cart(request, slug):
    username = request.user.username
    price = Item.objects.get(slug=slug).price
    discounted_price = Item.objects.get(slug=slug).discounted_price
    # quantity = Item.objects.get(slug=slug).quantity

    if discounted_price > 0:
        original_price = discounted_price
    else:
        original_price = price
    if Cart.objects.filter(username = username, slug = slug, checkout = False).exists():
        quantity = Cart.objects.get(username = username, slug=slug, checkout=False).quantity
        quantity = quantity + 1
        total = original_price * quantity
        Cart.objects.filter(username=username, slug=slug, checkout=False).update(quantity=quantity, total=total)
        return render(request, "cart.html")
    else:
        quantity = 1
    total = original_price * quantity

    data = Cart.objects.create(
        username = username,
        items = Item.objects.filter(slug=slug)[0],
        slug = slug,
        quantity = quantity,
        total = total
    )
    data.save()
    return render(request, "cart.html")

class CartView(BaseView):
    def get(self, request):
        username = request.user.username
        self.views['my_cart'] = Cart.objects.filter(username=username, checkout=False)
        return render(request, "cart.html", self.views)

home/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.views import View
from home.models import Category, Ad, Brand, Item, Slider
from cart.models import Cart, Item



# Create your views here.

class BaseView(View):
    views = {}
    views["category"] = Category.objects.filter(status = "active")
    views["new"] = Item.objects.filter(status="active", label="news")
    views["hots"] = Item.objects.filter(status="active", label="hot")

    # def get(self, request):
    #     username = request.user.username
    #     views["total_quantity"] = Item.objects.filter(username=username, checkout=False)


class HomeView(BaseView):
    def get(self, request):
        self.views["slider"] = Slider.objects.filter(status="active")
        self.views["ads"] = Ad.objects.all()
        self.views["brand"] = Brand.objects.filter(status="active")
        
        return render(request, "index.html", self.views)
    
class CategoryItemView(BaseView):
    def get(self, request, slug):
        category_id = Category.objects.get(slug=slug).id
        self.views["cat_items"] = Item.objects.filter(category = category_id)
        
        return render(request, "category.html", self.views)
    

class ItemSearchVeiw(BaseView):
    def get(self, request):
        search = request.GET.get('search', None)
        if search is None:
            return redirect("/")
        else:
            self.views['search_item'] = Item.objects.filter(name__icontains=search)
            return render(request, "search.html", self.views)
        return render(request, "category.html", self.views)
    
class ItemDetailView(BaseView):
    def get(self, request, slug):
        self.views['item_details'] = Item.objects.filter(slug=slug)
        return render(request, "product-detail.html", self.views)
    
    
def signup(request):
    if request.method =="POST":
        f_name = request.POST["first_name"]
        l_name = request.POST["last_name"]
        email = request.POST["email"]
        username = request.POST["username"]
        password = request.POST["password"]
        c_password = request.POST["cpassword"]
        if password == c_password:
            if User.objects.filter(username=username).exists():
                messages.error(request, "This username is already taken.")
                return redirect("home:signup")
            elif User.objects.filter(email=email).exists():
                messages.error(request, "This email is already taken.")
                return redirect("home:singup")
            else: 
                user = User.objects.create_user(
                    username = username,
                    email = email,
                    password = password,
                    first_name = f_name,
                    last_name = l_name
                )
                user.save()
                messages.success(request, "You are successfully registered.")
                return redirect("home:signup")
        else:
            messages.error(request, "Password Not Matched.")
            return redirect("home:signup")
    return render(request, "signup.html")


# Default Login
# def login(request):
#     return render(request, "registration/login.html")

# Custom Login and it use normal login.html template
def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return render(request, 'index.html')
        else:
            messages.error(request, "Wrong username or password")
            return redirect("home:login")

    return render(request, "login.html")

def logout(request):
    auth.logout(request)
    return render(request, "index.html")

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>E Store - eCommerce HTML Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download"
            name="description">

        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link
            href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap"
            rel="stylesheet">

        <!-- CSS Libraries -->
        <link
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            rel="stylesheet">
        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
            rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Top bar Start -->
        <div class="top-bar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <i class="fa fa-envelope"></i>
                        support@email.com
                    </div>
                    <div class="col-sm-6">
                        <i class="fa fa-phone-alt"></i>
                        +012-345-6789
                    </div>
                </div>
            </div>
        </div>
        <!-- Top bar End -->

        <!-- Nav Bar Start -->
        <div class="nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler"
                        data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div
                        class="collapse navbar-collapse justify-content-between"
                        id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="/"
                                class="nav-item nav-link active">Home</a>
                            <a href="product-list.html"
                                class="nav-item nav-link">Products</a>
                            <a href="product-detail.html"
                                class="nav-item nav-link">Product Detail</a>
                            <a href="cart.html"
                                class="nav-item nav-link">Cart</a>
                            <a href="checkout.html"
                                class="nav-item nav-link">Checkout</a>
                            <a href="my-account.html"
                                class="nav-item nav-link">My Account</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle"
                                    data-toggle="dropdown">More Pages</a>
                                <div class="dropdown-menu">
                                    <a href="wishlist.html"
                                        class="dropdown-item">Wishlist</a>
                                    <a href="#"
                                        class="dropdown-item">Login &
                                        Register</a>
                                    <a href="contact.html"
                                        class="dropdown-item">Contact Us</a>
                                </div>
                            </div>
                        </div>
                        {% if user.is_authenticated %}
                        <div class="navbar-nav ml-auto">
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle"
                                    data-toggle="dropdown">{{ user.username }}</a>
                                <div class="dropdown-menu">
                                    <a href="logout" class="dropdown-item">Logout</a>
<!--                                    <a href="{% url 'home:signup' %}"-->
<!--                                        class="dropdown-item">Register</a>-->
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="navbar-nav ml-auto">
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle"
                                    data-toggle="dropdown">User Account</a>
                                <div class="dropdown-menu">
                                    <a href="login " class="dropdown-item">Login</a>
                                    <a href="{% url 'home:signup' %}"
                                        class="dropdown-item">Register</a>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->

        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="/">
                                <img src="{% static 'img/logo.png' %}"
                                    alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <form method="GET" action="{% url 'home:search' %}">
                            <div class="search">
                                <input name="search" type="text" placeholder="Search">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-3">
                        <div class="user">
                            <a href="wishlist.html" class="btn wishlist">
                                <i class="fa fa-heart"></i>
                                <span>(0)</span>
                            </a>
                            <a href="cart" class="btn cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span>(0)</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End -->

        {% block content %}
        {% endblock %}

        <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Get in Touch</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>123 E Store,
                                    Los Angeles, USA</p>
                                <p><i
                                        class="fa fa-envelope"></i>email@example.com</p>
                                <p><i class="fa fa-phone"></i>+123-456-7890</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Follow Us</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href><i class="fab fa-twitter"></i></a>
                                    <a href><i
                                            class="fab fa-facebook-f"></i></a>
                                    <a href><i
                                            class="fab fa-linkedin-in"></i></a>
                                    <a href><i class="fab fa-instagram"></i></a>
                                    <a href><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Company Info</h2>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Terms & Condition</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Purchase Info</h2>
                            <ul>
                                <li><a href="#">Pyament Policy</a></li>
                                <li><a href="#">Shipping Policy</a></li>
                                <li><a href="#">Return Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>We Accept:</h2>
                            <img src="{% static 'img/payment-method.png' %}"
                                alt="Payment Method" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Secured By:</h2>
                            <img src="{% static 'img/godaddy.svg' %}"
                                alt="Payment Security" />
                            <img src="{% static 'img/norton.svg' %}"
                                alt="Payment Security" />
                            <img src="{% static 'img/ssl.svg' %}"
                                alt="Payment Security" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="https://htmlcodex.com">HTML
                                Codex</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">HTML
                                Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

home/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Cart</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Cart Start -->
        <div class="cart-page">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="cart-page-inner">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>Product</th>
                                            <th>Price</th>
                                            <th>Quantity</th>
                                            <th>Total</th>
                                            <th>Remove</th>
                                        </tr>
                                    </thead>
                                    <tbody class="align-middle">
                                    {% for cart in my_cart%}
                                        <tr>
                                            <td>
                                                <div class="img">
                                                    <a href="#"><img src="{{cart.items.image.url}}" alt="Image"></a>
                                                    <p>{{cart.items.name}}</p>
                                                </div>
                                            </td>
                                            {% if cart.items.discounted_price > 0 %}
                                            <td>Rs. {{ cart.items.discounted_price }}</td>
                                            {% else %}
                                            <td>Rs. {{ cart.items.price }}</td>
                                            {% endif %}
                                            <td>
                                                <div class="qty">
                                                    <button class="btn-minus"><i class="fa fa-minus"></i></button>
                                                    <input type="text" value="1">
                                                    <button class="btn-plus"><i class="fa fa-plus"></i></button>
                                                </div>
                                            </td>
                                            <td>$99</td>
                                            <td><button><i class="fa fa-trash"></i></button></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="cart-page-inner">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="coupon">
                                        <input type="text" placeholder="Coupon Code">
                                        <button>Apply Code</button>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="cart-summary">
                                        <div class="cart-content">
                                            <h1>Cart Summary</h1>
                                            <p>Sub Total<span>$99</span></p>
                                            <p>Shipping Cost<span>$1</span></p>
                                            <h2>Grand Total<span>$100</span></h2>
                                        </div>
                                        <div class="cart-btn">
                                            <button>Update Cart</button>
                                            <button>Checkout</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Cart End -->
{% endblock %}

home/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!-- Login Start -->
<div class="login">
    <div class="container-fluid">
        <div class="row">

            <div class="col-lg-6">
                <div class="login-form">
                    <p style="color:red, font:bold">{{ message }}</p>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row">


                            <div class="col-md-6">
                                <label>Username</label>
                                <input class="form-control" type="text" placeholder="Username" name="username">
                            </div>
                            <div class="col-md-6">
                                <label>Password</label>
                                <input class="form-control" type="text" placeholder="Password" name="password">

                                <div class="col-md-12">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="newaccount">
                                        <label class="custom-control-label" for="newaccount">Keep me signed in</label>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button class="btn">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Login End -->
    {% endblock %}

home/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Products</a></li>
            <li class="breadcrumb-item active">Login & Register</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Login Start -->
<div class="login">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="register-form">
                    <form method="POST">
                            {% csrf_token %}
                        {% for message in messages %}
                        <center> <font color="red" >{{ message }}</font></center>
                        {% endfor %}
                    <div class="row">

                        <div class="col-md-6">
                            <label>First Name</label>
                            <input class="form-control" type="text"
                                placeholder="First Name" name="first_name">
                        </div>
                        <div class="col-md-6">
                            <label>Last Name"</label>
                            <input class="form-control" type="text"
                                placeholder="Last Name" name="last_name">
                        </div>
                        <div class="col-md-6">
                            <label>E-mail</label>
                            <input class="form-control" type="text"
                                placeholder="E-mail" name="email">
                        </div>
                        <div class="col-md-6">
                            <label>Username</label>
                            <input class="form-control" type="text"
                                placeholder="Username" name="username">
                        </div>
                        <div class="col-md-6">
                            <label>Password</label>
                            <input class="form-control" type="password"
                                placeholder="Password" name="password">
                        </div>
                        <div class="col-md-6">
                            <label>Retype Password</label>
                            <input class="form-control" type="password"
                                placeholder="Password" name="cpassword">
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn">Submit</button>
                        </div>

                    </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
<!-- Login End -->
{% endblock %}